# Generated by Django 6.0.1 on 2026-01-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='others',
            field=models.TextField(blank=True),
        ),
    ]
