# Generated by Django 6.0.1 on 2026-01-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_item_others'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='others',
        ),
    ]
